title: fiddlybits
# email: your-email@example.com
url: "https://sea.nkelley.me/"
date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - behind-the-scenes/
  - TODO.md
