title: fiddlybits
url: "https://blog.sea.nkelley.me"
date_format: "%Y-%m-%d"
permalink: /:title
exclude:
  - scripts/
  - hooks/
  - .yarn/
  - TODO.md
  - README.md
  - build.sh
  - package.json
  - tsconfig.json
  - yarn.lock
sass:
  sourcemap: never
kramdown:
  show_warnings: true
default_anchor_headings:
  anchor_body: "#"
