title: fiddlybits
url: "https://blog.sea.nkelley.me"
date_format: "%Y-%m-%d"
permalink: pretty
exclude:
  - behind-the-scenes/
  - hooks/
  - TODO.md
  - README.md
sass:
  sourcemap: never
kramdown:
  show_warnings: true
