version: 2.1
orbs:
  ruby: circleci/ruby@1.0
job_defaults: &job_defaults
  docker:
    - image: cimg/ruby:3.0.1
  working_directory: ~/repo
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Jekyll Build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer
          command: bundle exec htmlproofer ./_site --check-html --disable-external --allow-hash-href
  deploy:
    <<: *job_defaults
    environment:
      - TARGET_BRANCH: gh-pages
      - DEPLOY_EMAIL: circleci-deploy-task@nope.nope
      - DEPLOY_NAME: CircleCI Deploy Task
    steps:
      - deploy:
          name: Commit to gh-pages
          command: |
            git config --global user.email "$DEPLOY_EMAIL"
            git config --global user.name "$DEPLOY_NAME"

            git checkout "$TARGET_BRANCH" || git checkout --orphan "$TARGET_BRANCH"
            git reset

            find . -depth 1 -not -name '_site' -not -name '.git' | xargs rm -rf
            mv _site/* .
            rmdir _site

            git add .
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

            # git push origin "$TARGET_BRANCH"

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
