#!/bin/bash

set -euo pipefail

for f in $(git diff --cached --name-only --diff-filter=d) ; do
  if [[ "$(file "$f")" =~ "image data" ]]; then
    output="$(identify -verbose "$f" | grep -i exif)" || true
    if [ -n "$output" ] ; then
      echo "Failing commit: $f has EXIF data!"
      echo "  $output"
      echo "Reminder: use strip-exif script on it if appropriate."
      exit 1
    fi
  fi
done

exit 0
