#!/bin/zsh

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

usage() {
  echo "$1 <title> [year]"
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ] ; then
  usage "$0"
  exit 0
fi

if [ "$#" -eq 0 ] || [ "$#" -gt 2 ] ; then
  usage "$0"
  exit 0
fi

title="$1"
year="${2:-}"

if ! command -v hxselect > /dev/null ; then
  echo 'hxselect not installed; please run:'
  echo '  brew install html-xml-utils'
  exit 1
fi

USER_AGENT_HEADER='User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0'
MAXIMUM_FILE_SIZE=204800 # 200KB; arbitrary
TARGET_WIDTH=600

movie_id="$(curl "https://www.imdb.com/find/?q=$(echo "$title" | tr ' ' '+')+$year"  --compressed -s -H "$USER_AGENT_HEADER" \
  | hxnormalize -x \
  | hxselect -s '\n' '.ipc-metadata-list-summary-item__t::attr(href)' \
  | sed -E 's|.*title/(tt[[:digit:]]+)/.*|\1|g' \
  | head -n1)"
movie_url="https://www.imdb.com/title/$movie_id/"
echo "movie URL: $movie_url"

curl "$movie_url" --compressed -s -H "$USER_AGENT_HEADER" > /tmp/movie_page.html
inferred_year="$(cat /tmp/movie_page.html \
  | hxnormalize -x \
  | hxselect -s '\n' "a[href^='/title/$movie_id/releaseinfo']" \
  | tr -d '\n' \
  | tr -d ' ' \
  | sed -E 's|.*>([[:digit:]]{4}).?([[:digit:]]{4})?<.*|\1|g')"

if [ -z "$year" ] ; then
  year="$inferred_year"
  echo "inferred year as $year"
elif [ "$year" -ne "$inferred_year" ] ; then
  echo "inferred year is different from given; we probably have the wrong movie"
  exit 1
fi

if cat /tmp/movie_page.html \
  | hxnormalize -x \
  | hxselect -c -s '\n' '[data-testid="hero__pageTitle"] + * > :first-child' \
  | head -n1 \
  | grep -q 'TV' ; then
  kind="tv"
else
  kind="movie"
fi
echo "media kind: $kind"

poster_viewer_id="$(cat /tmp/movie_page.html \
  | hxnormalize -x \
  | hxselect -s '\n' '.ipc-poster a.ipc-lockup-overlay::attr(href)' \
  | sed -E 's|.*mediaviewer/(rm[[:digit:]]+)/.*|\1|g' \
  | head -n1)"
poster_url="https://www.imdb.com/title/$movie_id/mediaviewer/$poster_viewer_id/"
echo "poster viewer URL: $poster_url"

image_url="$(curl "$poster_url" --compressed -s -H "$USER_AGENT_HEADER" \
  | hxnormalize -x \
  | hxselect -s '\n' 'img[data-image-id]:not(.peek)::attr(src)' \
  | sed -E 's|src="([^"]+)"|\1|g' \
  | head -n1)"
echo "poster image URL: $image_url"

# this is some garbage bash-ism
extension="${image_url##*.}"
# note that this script cd's into the repo root
output_path="assets/movies/$(echo "$title" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')-$year.$extension"

curl "$image_url" -s > "$output_path"

image_size="$(stat -f %z "$output_path")"
if [ "$image_size" -gt "$MAXIMUM_FILE_SIZE" ] ; then
  if [ "$(identify -ping -format '%w' "$output_path")" -lt "$TARGET_WIDTH" ] ; then
    echo 'image is too large on disk, but under maximum width, so not resizing'
  else
    echo "image too large ($image_size bytes); resizing"
    # per docs, a single number is assumed to be width and the height calculated to preserve aspect ratio
    convert "$output_path" -resize "$TARGET_WIDTH" /tmp/resized
    mv /tmp/resized "$output_path"

    image_size="$(stat -f %z "$output_path")"
    if [ "$image_size" -gt "$MAXIMUM_FILE_SIZE" ] ; then
      echo "image is still too large after resizing ($image_size bytes); continuing anyway"
    else
      echo "image resized to $image_size bytes"
    fi
  fi
fi

scripts/strip-exif "$output_path"
rm "${output_path}_original"

open "$output_path"
echo "file at $output_path"

# weird syntax via https://stackoverflow.com/questions/10587615/unix-command-to-prepend-text-to-a-file#comment74536218_10587615
<<(echo "- title: $title
  year: $year
  kind: $kind
  link: $movie_url
  poster: $(basename "$output_path")
  watched: $(date "+%Y-%m-%d")
  # watched-display:
  watch-this-if:
  dont-watch-this-because:
  more-thoughts: |
    ") < _data/movies.yml | sponge _data/movies.yml

echo "added entry to beginning of movies.yml"
